export default {
  id: "orcarouter",
  priority: 110,
  alias: "orcarouter",
  aliases: ["orca"],
  uiAlias: "orca",
  display: {
    name: "OrcaRouter",
    icon: "hub",
    color: "#0284C7",
    textIcon: "ORCA",
    website: "https://www.orcarouter.ai",
    notice: {
      text: "OpenAI-compatible adaptive routing gateway. 200+ models across frontier and open-source.",
      apiKeyUrl: "https://www.orcarouter.ai/console/api-keys",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.orcarouter.ai/v1/chat/completions",
    validateUrl: "https://api.orcarouter.ai/v1/models",
    thinkingFormat: "openai",
  },
  models: [
    { id: "orcarouter/auto", name: "Auto (smart routing)" },
    { id: "openai/gpt-5.5", name: "GPT-5.5", capabilities: ["vision"] },
    { id: "openai/gpt-6-astra", name: "GPT-6 Astra", capabilities: ["vision"] },
    { id: "google/gemini-3.8-flash", name: "Gemini 3.8 Flash", capabilities: ["vision"] },
    { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash", capabilities: ["vision"] },
    { id: "anthropic/claude-opus-5", name: "Claude Opus 5", capabilities: ["vision"] },
    { id: "anthropic/claude-opus-4.8", name: "Claude Opus 4.8", capabilities: ["vision"] },
    { id: "anthropic/claude-sonnet-4.6", name: "Claude Sonnet 4.6", capabilities: ["vision"] },
    { id: "grok/grok-4.3", name: "Grok 4.3", capabilities: ["vision"] },
    { id: "deepseek/deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "minimax/minimax-m2.7", name: "MiniMax M2.7" },
    { id: "qwen/qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "qwen/qwen3.8-max-0902", name: "Qwen3.8 Max" },
  ],
  serviceKinds: ["llm", "imageToText"],
  modelsFetcher: { url: "https://api.orcarouter.ai/v1/models", type: "openai" },
  passthroughModels: true,
  features: { usage: false, usageApikey: false },
};
