export default {
  id: "tokenharbor",
  priority: 110,
  alias: "tokenharbor",
  aliases: ["th"],
  uiAlias: "th",
  display: {
    name: "Token Harbor",
    icon: "anchor",
    color: "#0D9488",
    textIcon: "TH",
    website: "https://tokenharbor.ai",
    notice: {
      text: "Unified API gateway for frontier AI models (OpenAI-compatible). Free $5 credit for new accounts.",
      apiKeyUrl: "https://tokenharbor.ai/dashboard",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://tokenharbor.ai/v1/chat/completions",
    validateUrl: "https://tokenharbor.ai/v1/models",
    thinkingFormat: "openai",
  },
  models: [
    { id: "openai/gpt-5.6-sol", name: "GPT-5.6 Sol", capabilities: ["vision"] },
    { id: "openai/gpt-6-astra", name: "GPT-6 Astra", capabilities: ["vision"] },
    { id: "anthropic/claude-opus-5", name: "Claude Opus 5", capabilities: ["vision"] },
    { id: "anthropic/claude-opus-4.8", name: "Claude Opus 4.8", capabilities: ["vision"] },
    { id: "google/gemini-3.8-flash", name: "Gemini 3.8 Flash", capabilities: ["vision"] },
    { id: "google/gemini-3.5-flash", name: "Gemini 3.5 Flash", capabilities: ["vision"] },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "qwen/qwen3.8-max", name: "Qwen3.8 Max" },
    { id: "moonshotai/kimi-k3", name: "Kimi K3" },
    { id: "xiaomi/mimo-v2.5", name: "Xiaomi MiMo V2.5" },
  ],
  serviceKinds: ["llm", "imageToText"],
  modelsFetcher: { url: "https://tokenharbor.ai/v1/models", type: "openai" },
  passthroughModels: true,
  features: { usage: false, usageApikey: false },
};
