"use client";

import {
  Activity,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  AudioLines,
  Badge,
  Ban,
  BarChart,
  Bolt,
  BookOpen,
  Bot,
  Braces,
  Brackets,
  Brain,
  Brush,
  Bug,
  Building2,
  ChartLine,
  ChartPie,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleDot,
  CircleHelp,
  CircleUser,
  CircleX,
  Clapperboard,
  Clock,
  Cloud,
  CloudCheck,
  CloudOff,
  CloudSync,
  CloudUpload,
  Code,
  Coins,
  Computer,
  Contrast,
  Cookie,
  Copy,
  Cpu,
  CreditCard,
  Database,
  Delete,
  Diamond,
  Download,
  Edit,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FilePen,
  FileUp,
  FilterX,
  FlaskConical,
  FolderHeart,
  FolderX,
  Gauge,
  Gavel,
  GitFork,
  Globe,
  GlobeOff,
  GripVertical,
  HeartHandshake,
  History,
  Home,
  Hourglass,
  Image,
  ImageOff,
  Images,
  Inbox,
  Info,
  Key,
  KeyRound,
  Languages,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Link,
  Link2Off,
  List,
  ListChecks,
  ListPlus,
  ListX,
  LoaderCircle,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Menu,
  Mic,
  Minus,
  Monitor,
  Moon,
  Music,
  Network,
  Option,
  Package,
  PauseCircle,
  PiggyBank,
  Play,
  Plus,
  Power,
  Puzzle,
  Receipt,
  RefreshCw,
  Rocket,
  RotateCcw,
  Route,
  Save,
  Search,
  SearchX,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquareCheck,
  SquareCheckBig,
  Star,
  Sun,
  Table,
  Tag,
  Terminal,
  Timer,
  TimerOff,
  ToggleLeft,
  ToggleRight,
  Trash2,
  TriangleAlert,
  Trophy,
  Upload,
  User,
  Users,
  Verified,
  Wand2,
  Wifi,
  Wrench,
  X,
} from "lucide-react";

const ICON_MAP = {
  0: Circle,
  account_circle: CircleUser,
  account_tree: GitFork,
  add: Plus,
  add_chart: ChartLine,
  alt_route: Route,
  amber: AlertTriangle,
  api: Braces,
  api_key: KeyRound,
  apps: LayoutGrid,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  asc: ArrowUp,
  auto_awesome: Sparkles,
  auto_delete: Trash2,
  auto_fix_high: Wand2,
  badge: Badge,
  bar_chart: BarChart,
  block: Ban,
  bolt: Bolt,
  broken_image: ImageOff,
  brush: Brush,
  bug_report: Bug,
  build: Wrench,
  business: Building2,
  cancel: CircleX,
  check: Check,
  check_box: SquareCheck,
  check_box_outline_blank: Square,
  check_circle: CheckCircle,
  checklist: ListChecks,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  clear_all: ListX,
  close: X,
  cloud: Cloud,
  cloud_done: CloudCheck,
  cloud_off: CloudOff,
  cloud_sync: CloudSync,
  cloud_upload: CloudUpload,
  code: Code,
  codeblock: Code,
  computer: Computer,
  content_copy: Copy,
  contrast: Contrast,
  cookie: Cookie,
  dark: Moon,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  data_array: Brackets,
  data_object: Braces,
  data_usage: ChartPie,
  database: Database,
  delete: Delete,
  delete_sweep: Trash2,
  deployed_code: Package,
  diamond: Diamond,
  dns: Server,
  download: Download,
  drag_indicator: GripVertical,
  edit: Edit,
  edit_note: FilePen,
  error: CircleAlert,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  extension: Puzzle,
  file_upload: Upload,
  filter_alt_off: FilterX,
  folder_off: FolderX,
  folder_special: FolderHeart,
  format_list_bulleted: List,
  gavel: Gavel,
  graphic_eq: AudioLines,
  grid_view: LayoutGrid,
  groups: Users,
  help: CircleHelp,
  help_outline: CircleHelp,
  history: History,
  home: Home,
  horizontal_rule: Minus,
  hourglass_empty: Hourglass,
  hourglass_top: Hourglass,
  hub: Network,
  image: Image,
  image_search: Image,
  inbox: Inbox,
  index: List,
  info: Info,
  input: LogIn,
  key: Key,
  key_off: KeyRound,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  label: Tag,
  lan: Network,
  language: Languages,
  layers: Layers,
  leaderboard: Trophy,
  light: Sun,
  light_mode: Sun,
  link: Link,
  link_off: Link2Off,
  list: List,
  lock: Lock,
  lock_open: LockOpen,
  logout: LogOut,
  memory: Cpu,
  menu: Menu,
  menu_book: BookOpen,
  mic: Mic,
  model: Cpu,
  model_training: Brain,
  monitor: Monitor,
  monitoring: Activity,
  more_horiz: Ellipsis,
  more_vert: EllipsisVertical,
  movie: Clapperboard,
  music_note: Music,
  network_check: Activity,
  neurology: Brain,
  none: Circle,
  ok: CheckCircle,
  open_in_new: ExternalLink,
  option: Option,
  output: LogOut,
  pause_circle: PauseCircle,
  payments: CreditCard,
  perm_media: Images,
  person: User,
  play_arrow: Play,
  playlist_add: ListPlus,
  power_settings_new: Power,
  progress_activity: LoaderCircle,
  psychology: Brain,
  public: Globe,
  public_off: GlobeOff,
  radio_button_checked: CircleDot,
  radio_button_unchecked: Circle,
  receipt_long: Receipt,
  record_voice_over: Mic,
  refresh: RefreshCw,
  report_problem: TriangleAlert,
  restart_alt: RotateCcw,
  restore: RotateCcw,
  rocket_launch: Rocket,
  route: Route,
  save: Save,
  savings: PiggyBank,
  schedule: Clock,
  science: FlaskConical,
  search: Search,
  search_off: SearchX,
  select_all: SquareCheckBig,
  settings: Settings,
  shield: Shield,
  shield_with_heart: ShieldCheck,
  smart_toy: Bot,
  speed: Gauge,
  star: Star,
  stop: Square,
  stream: Activity,
  success: CheckCircle,
  swap_calls: ArrowLeftRight,
  swap_horiz: ArrowLeftRight,
  swap_vert: ArrowUpDown,
  sync: RefreshCw,
  sync_alt: ArrowLeftRight,
  table_chart: Table,
  terminal: Terminal,
  timer: Timer,
  timer_off: TimerOff,
  toggle_off: ToggleLeft,
  toggle_on: ToggleRight,
  toll: Coins,
  translate: Languages,
  travel_explore: Globe,
  tune: SlidersHorizontal,
  upload: Upload,
  upload_file: FileUp,
  verified: Verified,
  visibility: Eye,
  visibility_off: EyeOff,
  volunteer_activism: HeartHandshake,
  vpn_key: KeyRound,
  warning: TriangleAlert,
  wifi: Wifi,
  wifi_tethering: Wifi,
};

export default function Icon({ name, size = 18, className, ...props }) {
  const Cmp = ICON_MAP[name] || CircleHelp;
  return <Cmp size={size} className={className} aria-hidden="true" {...props} />;
}
